version: "3.9"
services:
  backend:
    build: ./backend
    container_name: personal_backend
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/mydb
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: personal_frontend
    ports:
      - "3000:80"

  db:
    image: postgres:15
    container_name: personal_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"  # ECS 內部用，不必對外開放
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
